import { convertFileSrc, invoke } from "@tauri-apps/api/core";
import type { Animation, AnimationDirectionMeta, AnimationFrameScoreReport, AnimationInput, AnimationTemplate, Asset, AssetPack, AssetVersion, BackgroundJob, BrushStamp, CharacterAnchor, CharacterAnchorSummary, CharacterProfile, CharacterContractReport, CharacterPackExportResult, CleanAlphaReport, ContractRetryResult, Conversation, DirectionSetResult, ExportAnimationPreviewResult, ExportResult, FacingCheckReport, FrameOptimizationResult, GenerationManifest, GenerationSession, HardenAnimationOptions, HardenAnimationReport, ImageProviderInput, InterpolateRigAnimationFramesResult, InterpolateRigFramesResult, ListMissingMotionsResult, Message, MirrorAnimationResult, MotionBatchResult, MotionPlan, MotionPresetCatalog, PaintFrameAlphaResult, ProductionScoreReport, ProceduralVfxInput, ProjectBackup, ProviderConnectionTest, ProviderInstallResult, ProviderRequestOptions, ProviderStatus, PythonRuntimeStatus, QualityReport, ReferenceCategory, ReferenceImage, RefineGenerationPromptInput, RegionMaskRect, RegionRegenResult, RigFitReport, RigInput, RigRenderResult, RigSuggestion, Rig, SharedPaletteReport, SidebarSnapshot, SizeContractReport, SplitStripResult, SpriteSheet, SpriteSheetInput, StripScoreReport, SubsampleVideoFramesResult, TemplateApplication, TerrainExportInput, TerrainExportResult, VfxEffect, Workspace, Worktree, WorktreeKind, WorkspaceRigSpec } from "$lib/types";

export const api = {
  listWorkspaces: () => invoke<Workspace[]>("list_workspaces"),
  loadSidebarState: (workspaceId?: string) => invoke<SidebarSnapshot>("load_sidebar_state", { workspaceId: workspaceId ?? null }),
  createWorkspace: (name: string, path: string) => invoke<Workspace>("create_workspace", { name, path }),
  openWorkspace: (path: string) => invoke<Workspace>("open_workspace", { path }),
  checkPythonRuntime: () => invoke<PythonRuntimeStatus>("check_python_runtime"),
  touchWorkspace: (id: string) => invoke<Workspace>("touch_workspace", { id }),
  renameWorkspace: (id: string, name: string) => invoke<void>("rename_workspace", { id, name }),
  removeWorkspace: (id: string) => invoke<void>("remove_workspace", { id }),
  deleteWorkspace: (id: string) => invoke<void>("delete_workspace", { id }),
  createProjectBackup: (projectId: string, destinationDirectory: string) => invoke<ProjectBackup>("create_project_backup", { projectId, destinationDirectory }),
  restoreProjectBackup: (projectId: string, backupPath: string) => invoke<Workspace>("restore_project_backup", { projectId, backupPath }),
  importProjectBackup: (backupPath: string, destinationPath: string) => invoke<Workspace>("import_project_backup", { backupPath, destinationPath }),
  listWorktrees: (projectId: string) => invoke<Worktree[]>("list_worktrees", { projectId }),
  createWorktree: (projectId: string, name: string, kind: WorktreeKind, description?: string) => invoke<Worktree>("create_worktree", { projectId, name, kind, description }),
  updateWorktree: (id: string, name: string, description?: string) => invoke<Worktree>("update_worktree", { id, name, description }),
  deleteWorktree: (id: string) => invoke<void>("delete_worktree", { id }),
  listWorktreeAssetIds: (worktreeId: string) => invoke<string[]>("list_worktree_asset_ids", { worktreeId }),
  linkAssetToWorktree: (worktreeId: string, assetId: string, relationship: "owned" | "referenced" = "owned") => invoke<void>("link_asset_to_worktree", { worktreeId, assetId, relationship }),
  listConversations: (workspaceId: string, worktreeId?: string) => invoke<Conversation[]>("list_conversations", { workspaceId, worktreeId: worktreeId ?? null }),
  listArchivedConversations: (workspaceId: string) => invoke<Conversation[]>("list_archived_conversations", { workspaceId }),
  createConversation: (workspaceId: string, worktreeId?: string, title?: string, provider?: string) => invoke<Conversation>("create_conversation", { workspaceId, worktreeId: worktreeId ?? null, title, provider }),
  renameConversation: (id: string, title: string) => invoke<void>("rename_conversation", { id, title }),
  switchConversationProvider: (id: string, provider: string) => invoke<Conversation>("switch_conversation_provider", { id, provider }),
  archiveConversation: (id: string) => invoke<void>("archive_conversation", { id }),
  restoreConversation: (id: string) => invoke<Conversation>("restore_conversation", { id }),
  deleteConversation: (id: string) => invoke<void>("delete_conversation", { id }),
  listMessages: (conversationId: string) => invoke<Message[]>("list_messages", { conversationId }),
  recordChatTurn: (conversationId: string, userContent: string, assistantContent: string) =>
    invoke<Message[]>("record_chat_turn", { conversationId, userContent, assistantContent }),
  recordChatAssistant: (conversationId: string, assistantContent: string) =>
    invoke<Message[]>("record_chat_assistant", { conversationId, assistantContent }),
  updateMessageMetadata: (id: string, metadata: Record<string, unknown>) => invoke<void>("update_message_metadata", { id, metadata }),
  detectProviders: () => invoke<ProviderStatus[]>("detect_providers"),
  installAgentProvider: (providerId: string) => invoke<ProviderInstallResult>("install_agent_provider", { providerId }),
  authenticateAgentProvider: (providerId: string) => invoke<ProviderInstallResult>("authenticate_agent_provider", { providerId }),
  saveImageProvider: (input: ImageProviderInput) => invoke<ProviderStatus>("save_image_provider", { input }),
  deleteImageProvider: (id: string) => invoke<void>("delete_image_provider", { id }),
  testImageProvider: (input: ImageProviderInput) => invoke<ProviderConnectionTest>("test_image_provider", { input }),
  startProviderMessage: (conversationId: string, prompt: string, context?: string, options?: ProviderRequestOptions) => invoke<string>("start_provider_message", { conversationId, prompt, context, options }),
  cancelProviderRequest: (requestId: string) => invoke<void>("cancel_provider_request", { requestId }),
  refineGenerationPrompt: (input: RefineGenerationPromptInput) => invoke<string>("refine_generation_prompt_command", { input }),
  cancelRefineGenerationPrompt: (conversationId: string) => invoke<void>("cancel_refine_generation_prompt_command", { conversationId }),
  appendConversationLogEntry: (input: { conversationId: string; requestId?: string; level: string; category: string; eventType: string; message: string; details?: Record<string, unknown> }) =>
    invoke<void>("append_conversation_log_entry", { input }),
  exportConversationDebugLog: (input: { conversationId: string; destinationPath: string }) =>
    invoke<string>("export_conversation_debug_log", { input }),
  planMotion: (prompt: string, generation: ProviderRequestOptions["generation"]) => invoke<MotionPlan>("plan_motion", { prompt, generation }),
  scanAssets: (workspaceId: string) => invoke<Asset[]>("scan_assets", { workspaceId }),
  listAssets: (workspaceId: string) => invoke<Asset[]>("list_assets", { workspaceId }),
  getGenerationManifest: (workspaceId: string) => invoke<GenerationManifest | null>("get_generation_manifest", { workspaceId }),
  getGenerationFingerprint: (workspaceId: string) => invoke<string | null>("get_generation_fingerprint", { workspaceId }),
  listWorkspaceRigSpecs: (workspaceId: string) => invoke<WorkspaceRigSpec[]>("list_workspace_rig_specs", { workspaceId }),
  scanGenerationAssets: (workspaceId: string, worktreeId?: string) => invoke<Asset[]>("scan_generation_assets", { workspaceId, worktreeId }),
  listAssetPacks: (workspaceId: string) => invoke<AssetPack[]>("list_asset_packs", { workspaceId }),
  importAsset: (workspaceId: string, sourcePath: string, category: string) => invoke<Asset>("import_asset", { workspaceId, sourcePath, category }),
  renameAsset: (id: string, name: string) => invoke<Asset>("rename_asset", { id, name }),
  getAssetUsage: (id: string) => invoke<import("$lib/types").AssetUsage>("get_asset_usage", { id }),
  deleteAsset: (id: string, force = false) => invoke<void>("delete_asset", { id, force }),
  exportAsset: (id: string) => invoke<ExportResult>("export_asset", { id }),
  exportGodotTileset: (input: TerrainExportInput) => invoke<TerrainExportResult>("export_godot_tileset", { input }),
  listAssetVersions: (assetId: string) => invoke<AssetVersion[]>("list_asset_versions", { assetId }),
  listReferenceImages: (worktreeId: string) => invoke<ReferenceImage[]>("list_reference_images", { worktreeId }),
  importReferenceImage: (worktreeId: string, sourcePath: string, category: ReferenceCategory, notes?: string) => invoke<ReferenceImage>("import_reference_image", { worktreeId, sourcePath, category, notes }),
  importReferenceBytes: (worktreeId: string, fileName: string, bytes: number[], category: ReferenceCategory, notes?: string) => invoke<ReferenceImage>("import_reference_bytes", { worktreeId, fileName, bytes, category, notes }),
  updateReferenceImage: (id: string, name: string, category: ReferenceCategory, notes?: string) => invoke<ReferenceImage>("update_reference_image", { id, name, category, notes }),
  deleteReferenceImage: (id: string) => invoke<void>("delete_reference_image", { id }),
  setConversationReference: (conversationId: string, referenceId: string, active: boolean, strength?: number) => invoke<void>("set_conversation_reference", { conversationId, referenceId, active, strength }),
  listConversationReferenceIds: (conversationId: string) => invoke<string[]>("list_conversation_reference_ids", { conversationId }),
  listAnimations: (workspaceId: string, worktreeId?: string) => invoke<Animation[]>("list_animations", { workspaceId, worktreeId: worktreeId ?? null }),
  saveAnimation: (input: AnimationInput) => invoke<Animation>("save_animation", { input }),
  deleteAnimation: (id: string) => invoke<void>("delete_animation", { id }),
  exportAnimation: (id: string, destination?: string, format?: string) => invoke<ExportResult>("export_animation", { id, destination, format }),
  checkCharacterContract: (workspaceId: string, worktreeId: string, anchorSlug?: string) => invoke<CharacterContractReport>("check_character_contract", { workspaceId, worktreeId, anchorSlug }),
  exportCharacterPack: (input: { workspaceId: string; worktreeId: string; destination: string; anchorSlug?: string; metadataFormat?: string; includeAnimatedPreviews?: boolean }) => invoke<CharacterPackExportResult>("export_character_pack", { input }),
  exportAnimationPreview: (input: { animationId: string; destination?: string; format?: string }) => invoke<ExportAnimationPreviewResult>("export_animation_preview", { input }),
  listMissingMotions: (workspaceId: string, worktreeId: string, anchorSlug: string) => invoke<ListMissingMotionsResult>("list_missing_motions", { workspaceId, worktreeId, anchorSlug }),
  listGenerationSessions: (workspaceId: string, worktreeId?: string) => invoke<GenerationSession[]>("list_generation_sessions", { workspaceId, worktreeId }),
  getProductionScore: (workspaceId: string, worktreeId: string, anchorSlug?: string) => invoke<ProductionScoreReport>("get_production_score", { workspaceId, worktreeId, anchorSlug }),
  listJobs: (projectId: string, worktreeId?: string) => invoke<BackgroundJob[]>("list_jobs", { projectId, worktreeId: worktreeId ?? null }),
  cancelJob: (id: string) => invoke<BackgroundJob>("cancel_job", { id }),
  listSpriteSheets: (projectId: string, worktreeId?: string) => invoke<SpriteSheet[]>("list_sprite_sheets", { projectId, worktreeId: worktreeId ?? null }),
  queueSpriteSheet: (input: SpriteSheetInput) => invoke<BackgroundJob>("queue_sprite_sheet", { input }),
  deleteSpriteSheet: (id: string) => invoke<void>("delete_sprite_sheet", { id }),
  listVfxEffects: (projectId: string, worktreeId?: string) => invoke<VfxEffect[]>("list_vfx_effects", { projectId, worktreeId: worktreeId ?? null }),
  queueProceduralVfx: (input: ProceduralVfxInput) => invoke<BackgroundJob>("queue_procedural_vfx", { input }),
  getQualityReport: (animationId: string) => invoke<QualityReport | null>("get_quality_report", { animationId }),
  queueQualityAnalysis: (animationId: string) => invoke<BackgroundJob>("queue_quality_analysis", { animationId }),
  acknowledgeQualityCheck: (checkId: string, ignored = false) => invoke<void>("acknowledge_quality_check", { checkId, ignored }),
  optimizeAnimationFrames: (animationId: string, maxChanges = 3) => invoke<FrameOptimizationResult>("optimize_animation_frames", { input: { animationId, maxChanges } }),
  repairAnimationAlignment: (animationId: string) => invoke<Animation>("repair_animation_alignment", { animationId }),
  repairAnimationTransparency: (animationId: string) => invoke<Animation>("repair_animation_transparency", { animationId }),
  runSpritePolish: (workspaceId: string, master: string, rough: string, input: string, output: string) =>
    invoke<Record<string, unknown>>("run_sprite_polish", { workspaceId, master, rough, input, output }),
  archiveSpritePaths: (workspaceId: string, paths: string[], label: string) =>
    invoke<string[]>("archive_sprite_paths", { workspaceId, paths, label }),
  restoreSpritePaths: (workspaceId: string, backupPaths: string[], targetPaths: string[]) =>
    invoke<void>("restore_sprite_paths", { workspaceId, backupPaths, targetPaths }),
  listRigs: (workspaceId: string, worktreeId?: string) => invoke<Rig[]>("list_rigs", { workspaceId, worktreeId: worktreeId ?? null }),
  saveRig: (input: RigInput) => invoke<Rig>("save_rig", { input }),
  deleteRig: (id: string) => invoke<void>("delete_rig", { id }),
  validateRigSpec: (input: RigInput) => invoke<string[]>("validate_rig_spec", { input }),
  suggestRigPoints: (assetId: string, morphology?: string) => invoke<RigSuggestion>("suggest_rig_points", { assetId, morphology: morphology ?? null }),
  analyzeRigFit: (assetId: string) => invoke<RigFitReport>("analyze_rig_fit", { assetId }),
  aiSuggestRigPoints: (input: { assetId: string; morphology?: string; motion?: string; providerId?: string; model?: string; reasoningEffort?: string }) => invoke<RigSuggestion>("ai_suggest_rig_points", { input }),
  renderRigPreview: (input: RigInput) => invoke<string[]>("render_rig_preview", { input }),
  renderRigAnimation: (input: RigInput) => invoke<RigRenderResult>("render_rig_animation", { input }),
  interpolateRigFrames: (input: { rig: RigInput; fromIndex: number; toIndex: number; steps: number }) =>
    invoke<InterpolateRigFramesResult>("interpolate_rig_frames", { input: { rig: input.rig, fromIndex: input.fromIndex, toIndex: input.toIndex, steps: input.steps } }),
  interpolateRigAnimationFrames: (input: { rig: RigInput; fromIndex: number; toIndex: number; steps: number; animationId: string; workspaceId: string; worktreeId?: string }) =>
    invoke<InterpolateRigAnimationFramesResult>("interpolate_rig_animation_frames", { input }),
  queueRegionRegen: (input: { animationId: string; frameIndex: number; regions: RegionMaskRect[]; brushStrokes?: BrushStamp[]; conversationId: string; prompt?: string }) =>
    invoke<RegionRegenResult>("queue_region_regen", { input }),
  subsampleVideoFrames: (input: { workspaceId: string; assetIds: string[]; minDelta?: number; stride?: number }) =>
    invoke<SubsampleVideoFramesResult>("subsample_video_frames", { input }),
  quantizeWorktreePalette: (input: { workspaceId: string; worktreeId?: string; anchorSlug?: string; colorCount?: number }) =>
    invoke<SharedPaletteReport>("quantize_worktree_palette", { input }),
  paintFrameAlpha: (input: { assetId: string; strokes: BrushStamp[]; mode: "erase" | "restore"; versionId?: string }) =>
    invoke<PaintFrameAlphaResult>("paint_frame_alpha", { input }),
  restoreAssetVersion: (assetId: string, versionId: string) =>
    invoke<Asset>("restore_asset_version", { input: { assetId, versionId } }),
  listAnimationTemplates: (projectId: string) => invoke<AnimationTemplate[]>("list_animation_templates", { projectId }),
  createAnimationTemplate: (animationId: string, name: string, intent: string, motionDescription: string, frameMode: "fixed" | "auto", minFrames: number, maxFrames: number, generationPrompt = "", negativePrompt = "") => invoke<AnimationTemplate>("create_animation_template", { animationId, name, intent, motionDescription, frameMode, minFrames, maxFrames, generationPrompt, negativePrompt }),
  applyAnimationTemplate: (templateId: string, targetAssetId: string) => invoke<TemplateApplication>("apply_animation_template", { templateId, targetAssetId }),
  deleteAnimationTemplate: (id: string) => invoke<void>("delete_animation_template", { id }),
  getSetting: (key: string) => invoke<unknown>("get_setting", { key }),
  setSetting: (key: string, value: unknown) => invoke<void>("set_setting", { key, value }),
  promoteAnchor: (workspaceId: string, assetId: string, slug?: string, autoOrient = false, view?: string) => invoke<CharacterAnchor>("promote_anchor", { input: { workspaceId, assetId, slug, autoOrient, view } }),
  getAnchor: (workspaceId: string, slug: string) => invoke<CharacterAnchor>("get_anchor", { workspaceId, slug }),
  listAnchors: (workspaceId: string) => invoke<CharacterAnchorSummary[]>("list_anchors", { workspaceId }),
  getCharacterProfile: (workspaceId: string, slug: string) => invoke<CharacterProfile>("get_character_profile", { workspaceId, slug }),
  refreshCharacterProfile: (workspaceId: string, slug: string, worktreeId?: string) => invoke<CharacterProfile>("refresh_character_profile", { workspaceId, slug, worktreeId }),
  exportCharacterProfile: (input: { workspaceId: string; slug: string; destination: string }) => invoke<CharacterProfile>("export_character_profile", { input }),
  importCharacterProfile: (input: { workspaceId: string; sourcePath: string }) => invoke<CharacterProfile>("import_character_profile", { input }),
  detectAnchorFacing: (workspaceId: string, slug: string) => invoke<FacingCheckReport>("detect_anchor_facing", { workspaceId, slug }),
  listFacingChecks: (workspaceId: string, slug?: string) => invoke<FacingCheckReport[]>("list_facing_checks", { input: { workspaceId, slug } }),
  scoreAnimationFrames: (animationId: string) => invoke<AnimationFrameScoreReport>("score_animation_frames", { input: { animationId } }),
  orientAnchor: (workspaceId: string, slug: string) => invoke<CharacterAnchor>("orient_anchor", { input: { workspaceId, slug } }),
  mirrorAnimation: (input: { animationId: string; targetFacing: string; sourceFacing?: string; anchorSlug?: string }) => invoke<MirrorAnimationResult>("mirror_animation", { input }),
  queueDirectionSet: (input: { workspaceId: string; worktreeId: string; sourceAnimationId: string; anchorSlug: string; motion: string; set: "4" | "8"; conversationId?: string }) => invoke<DirectionSetResult>("queue_direction_set", { input }),
  listMotionPresets: (workspaceId: string) => invoke<MotionPresetCatalog>("list_motion_presets", { workspaceId }),
  saveMotionPresets: (workspaceId: string, catalog: MotionPresetCatalog) => invoke<MotionPresetCatalog>("save_motion_presets", { workspaceId, catalog }),
  queueMotionBatch: (input: { workspaceId: string; worktreeId: string; anchorSlug: string; motions?: string[]; set: "4" | "8"; conversationId?: string; hardenAfter?: boolean; seedAnimationId?: string; onlyMissing?: boolean }) => invoke<MotionBatchResult>("queue_motion_batch", { input }),
  listDirectionMeta: (workspaceId: string, worktreeId: string) => invoke<AnimationDirectionMeta[]>("list_direction_meta", { workspaceId, worktreeId }),
  hardenAnimation: (animationId: string, anchorSlug?: string, sourcePath?: string, frameCount?: number, conversationId?: string, options?: HardenAnimationOptions) => invoke<HardenAnimationReport>("harden_animation", { animationId, anchorSlug, sourcePath, frameCount, conversationId, options }),
  cleanAlphaAnimation: (animationId: string) => invoke<CleanAlphaReport>("clean_alpha_animation", { animationId }),
  snapToPixelGrid: (animationId: string, gridSize?: number) => invoke<Animation>("snap_to_pixel_grid", { animationId, gridSize }),
  normalizeAnimation: (input: { animationId: string; anchorSlug?: string; lockFirstFrame?: boolean; sharedScale?: boolean; padding?: number }) => invoke<Animation>("normalize_animation", { input }),
  splitSpriteStrip: (input: { workspaceId: string; sourcePath: string; layout: string; frameCount: number; columns?: number; recoverForeground?: boolean; category?: string }) => invoke<SplitStripResult>("split_sprite_strip", { input }),
  scoreSpriteStrip: (input: { sourcePath: string; frameCount?: number; layout?: string }) => invoke<StripScoreReport>("score_sprite_strip", { input }),
  extractVideoFrames: (input: { workspaceId: string; videoPath: string; fps?: number }) => invoke<SplitStripResult>("extract_video_frames", { input }),
  nudgeAnimationFrames: (input: { animationId: string; deltas: { frameIndex: number; offsetX: number; offsetY: number }[]; applyToAll?: boolean }) => invoke<Animation>("nudge_animation_frames", { input }),
  resetAnimationAlignmentOffsets: (animationId: string) => invoke<Animation>("reset_animation_alignment_offsets", { animationId }),
  checkSizeContract: (animationId: string, anchorSlug?: string) => invoke<SizeContractReport>("check_size_contract", { animationId, anchorSlug }),
  retrySizeContract: (input: { animationId: string; anchorSlug?: string; conversationId?: string; regenerate?: boolean; maxDeterministicPasses?: number }) => invoke<ContractRetryResult>("retry_size_contract", { input }),
  queueContractRetry: (input: { animationId: string; conversationId: string; anchorSlug?: string; maxAiAttempts?: number; maxDeterministicPasses?: number }) => invoke<ContractRetryResult>("queue_contract_retry", { input }),
  finalizeContractRetry: (input: { animationId: string; sourcePath: string; frameCount: number; anchorSlug?: string; layout?: string }) => invoke<ContractRetryResult>("finalize_contract_retry", { input }),
  setAnimationReviewStatus: (animationId: string, status: "draft" | "accepted" | "rejected") => invoke<Animation>("set_animation_review_status", { animationId, status }),
};

export const assetUrl = (path: string) => convertFileSrc(path);
