<script lang="ts">
  import { untrack } from "svelte";
  import { FileKey2, X } from "lucide-svelte";
  import { assetUrl } from "$lib/api";
  import type { AnimationTemplate, Asset } from "$lib/types";
  let { template, assets, busy=false, onApply, onClose }:{template:AnimationTemplate;assets:Asset[];busy?:boolean;onApply:(assetId:string)=>void|Promise<void>;onClose:()=>void}=$props();
  let targetId=$state(untrack(()=>assets[0]?.id??""));
</script>
<div class="backdrop" role="presentation" onclick={(event)=>event.target===event.currentTarget&&onClose()}><section class="dialog"><header><div><p>APPLY MOTION</p><h2>{template.name}</h2></div><button onclick={onClose}><X size={15}/></button></header><div class="summary"><FileKey2 size={18}/><div><strong>{template.frameMode === "auto" ? `${template.minFrames}–${template.maxFrames} frames` : `${template.preferredFrames} fixed frames`} · {template.fps} FPS</strong><p>{template.motionDescription}</p></div></div><div class="phases">{#each template.phases as phase}<span><b>{phase.position+1}</b>{phase.name}<small>{phase.frameCount}f</small></span>{/each}</div><label>Target master<select bind:value={targetId}><option value="" disabled>Select an asset</option>{#each assets as asset}<option value={asset.id}>{asset.name} · {asset.width}×{asset.height}</option>{/each}</select></label>{#if targetId}{@const target=assets.find(asset=>asset.id===targetId)}{#if target}<div class="target"><img src={assetUrl(target.path)} alt={target.name}/><div><strong>{target.name}</strong><p>The generated frames will preserve this exact master while following the template motion.</p></div></div>{/if}{/if}<footer><button onclick={onClose}>Cancel</button><button class="primary" disabled={busy||!targetId} onclick={()=>onApply(targetId)}>{busy?"Preparing…":"Prepare in chat"}</button></footer></section></div>
<style>.backdrop{position:fixed;inset:0;z-index:70;background:#000a;display:grid;place-items:center}.dialog{width:min(590px,calc(100vw - 30px));background:var(--surface);border:1px solid var(--border-strong);border-radius:10px;box-shadow:0 28px 90px #000b;padding:20px}header{display:flex;justify-content:space-between}header p{font-size:9px;letter-spacing:.15em;font-weight:700;color:var(--accent);margin:0 0 7px}h2{font-size:17px;margin:0}header button{border:0;background:transparent;color:var(--faint);cursor:pointer}.summary{display:grid;grid-template-columns:24px minmax(0,1fr);gap:9px;margin-top:18px;padding:12px;background:var(--bg);border:1px solid var(--border);border-radius:7px;color:var(--accent)}.summary strong{font-size:11px;color:var(--text)}.summary p{font-size:11px;line-height:1.45;color:var(--muted);margin:5px 0 0}.phases{display:flex;gap:5px;overflow:auto;margin:11px 0 18px}.phases span{min-width:max-content;border:1px solid var(--border);border-radius:5px;padding:6px 7px;font-size:10px;color:var(--muted)}.phases b{display:inline-grid;place-items:center;width:15px;height:15px;border-radius:50%;background:var(--selected);font-size:8px;margin-right:5px}.phases small{color:var(--faint);margin-left:6px}label{font-size:10px;color:var(--muted)}select{display:block;width:100%;height:33px;margin-top:5px;background:var(--bg);border:1px solid var(--border);border-radius:5px;color:var(--text);font:inherit;font-size:11px;padding:0 8px}.target{display:grid;grid-template-columns:58px minmax(0,1fr);gap:10px;align-items:center;margin-top:11px;padding:8px;border:1px solid var(--border);border-radius:6px;background:var(--bg)}.target img{width:58px;height:58px;object-fit:contain;image-rendering:pixelated;background:var(--preview)}.target strong{font-size:11px}.target p{font-size:10px;line-height:1.4;color:var(--faint);margin:4px 0 0}footer{display:flex;justify-content:flex-end;gap:7px;border-top:1px solid var(--border);padding-top:15px;margin-top:18px}footer button{height:31px;border:1px solid var(--border);border-radius:5px;background:var(--bg);color:var(--muted);font:inherit;font-size:11px;padding:0 11px;cursor:pointer}footer button.primary{background:var(--text);color:var(--bg);border-color:var(--text)}button:disabled{opacity:.45}</style>
